### ISSUE TITLE
There seems to be a graphical glitch

### ISSUE THREAD

**Issue by leeadama** [nimeral/AuctionatorVanilla#2]
The functionality seems to work, at least as far as searching for auctions and recommending a good price.

I didn't actually post any auctions using it.

But there were graphical glitches on the Auctionator screen.

You can see a screenshot here : https://1drv.ms/i/s!AkFJKno2myAmhfp-NuApGkwelTVq0A

Also, I noticed the scanning & database functions don't seem to be present.  Are you planning to add these in the future ?

**Comment by nimeral** [comment]
Yes, there's a glitch I didn't plan to fix (already reported actually https://github.com/nimeral/AuctionatorVanilla/issues/1). No, I didn't plan to add any features. It's a backport from Auctionator 1.0 where they weren't present. 

Besides, this "project" is 3 years old and I'm not planning to "develop" it. Just open-sourced it in case someone else finds it helpful (or maybe even worth updating).

Thanks for the report and your interest, and sorry to disappoint.

**Comment by leeadama** [comment]
Thanks for your reply.  I made some tweaks to the xml file that makes it look better for me.

You get see it here : https://pastebin.com/cXTkngv3

And I've attached it to this post.
[Auctionator.xml.zip](https://github.com/nimeral/AuctionatorVanilla/files/1691665/Auctionator.xml.zip)

The #1 bug report you linked mentioned UI Scale, but I am not using that setting, it’s turned off in my client.

These changes make it look right for me (With UI Scale turned off), that’s about all I know.

It looks like this for me now : https://1drv.ms/i/s!AkFJKno2myAmhfsjQtKOCdrCmeQWbw

I don’t know if my changes would help anyone or not I just thought I’d send it to you.

Thanks,

Robert

**Comment by nimeral** [comment]
Hi Robert,

Sorry for the late reply. 

The new xml only fixes the glitch for me in certain situations. My guess is that the cause is a combination of screen resolution and UI scale. For me, your xml looks best with 1360x768 resolution and like 0.9 UI scale. Disabled UI scale shifts the buttons in a different direction.

Anyway, I can recommend your fix to everyone who has issues with the glitch: it's likely to become better.
